# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

apiVersion: v1
name: etcd
home: https://github.com/coreos/etcd
version: 3.2.26
appVersion: 2.2.5
description: Distributed reliable key-value store for the most critical data of a
  distributed system.
-icon: https://raw.githubusercontent.com/coreos/etcd/master/logos/etcd-horizontal-color.png
sources:
- https://github.com/coreos/etcd
